"""
- Exceptions for datastructures module

"""

class EmptyQueueError(Exception): ...

class StackOverflowError(Exception): ... 

class EmptyStackError(Exception): ...

class EmptyTreeError(Exception): ...
