
name: CI

on : [push]

jobs:
    build:
        runs-on: ubuntu_latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.12'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install .

        - name: Lint code
          run: |
            ruff
            pylint --fail-under=8 src

        - name: Run tests
          run: |
            pytest
